### PR TITLE
Search

### PR DESCRIPTION
**Pull request by Megtails**
The current working iteration has it so we can search by a single criterion. I am still working on creating a version of this that will search based of multiple criteria, but I'm not there yet. But this works!

### CODE REVIEW

**Review by TanyaBuechel — APPROVED** [review]
Ran it on my computer and it worked as expected - ready to merge!

**Review by codeswitching9 — CHANGES_REQUESTED** [review]
I see that there are some conflicts. They're probably overlapping things like .json files, etc, so let's double check as a group first.

**Comment by wildNoodleBrain** [comment]
Ran good for me.

**Comment by wildNoodleBrain** [comment]
Ran properly for me

**Pull request closed without merging**
